version: '2'
services:
    hyecheonblog-app:
        image: hyecheonblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hyecheonblog-mysql:3306/hyecheonblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hyecheonblog-mysql:
        extends:
            file: mysql.yml
            service: hyecheonblog-mysql
